config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # /users/sign_up /users/sign_in
  devise_for :users

  root 'home#index'

  post 'toggle_like', to: 'likes#toggle_like', as: :toggle_like
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  # https://railsguides.jp/active_storage_overview.html
  has_many_attached :images

  validates :images, presence: true, blob: { content_type: :image } 

  has_many :likes
  has_many :likers, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :posts
  has_one_attached :profile_pic

  has_many :likes
end

app/controllers/application_controller.rb
#https://github.com/heartcombo/devise#strong-parameters

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    # /users/sign_up
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :phone_number, :full_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def toggle_like
    if(@like = @post.likes.find_by(user: current_user))
      @like.destroy
    else
      @post.likes.create(user: current_user)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "post#{@post.id}actions",
          partial: "posts/post_actions",
          locals: {post: @post}
        )
      end
    end
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_to root_path, status: :unprocessable_entity, alert: @post.errors.full_messages }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:caption, :longitude, :latitude, :user_id, :allow_comments, :show_likes_count, images: [])
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<%= render "layouts/flash_messages" %>

<div class="d-flex my-5 justify-content-center gap-5">
  <div class="d-flex flex-column gap-3">
    <%= render 'story/stories_list' %>

    <div class="flex flex-column">
      <% current_user.posts.each do |p| %>
        <%= render 'posts/post', post: p %>
      <% end %>
    </div>
  </div>

  <%= render 'suggestions/suggestions_list' %>
</div>

app/views/layouts/_flash_messages.html.erb
<% if notice && notice.is_a?(Array) %>
  <% notice.each do |n| %>
    <p class="alert alert-success">
      <%= n %>
    </p>
  <% end %>
<% elsif notice && notice.is_a?(String) %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
<% end %>

<% if alert && alert.is_a?(Array) %>
  <% alert.each do |a| %>
    <p class="alert alert-danger">
      <%= a %>
    </p>
  <% end %>
<% elsif alert && alert.is_a?(String) %>
  <p class="alert alert-danger">
    <%= alert %>
  </p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav
  class="navbar navbar-expand-lg bg-light sticky-top bg-white border-bottom
    border-dark"
  style="border-color: #afafaf"
>
  <div class="container-fluid w-75">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'logo.png', width: "100rem" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="d-flex">
      <div class="collapse navbar-collapse me-5" id="navbarSupportedContent">
        <form class="d-flex" role="search">
          <input class="form-control me-2 border-0" type="search" placeholder="Search" aria-label="Search" style="background: #efefef">
        </form>
      </div>

      <div class="navbar-collapse gap-4">
        <%= link_to root_path, class: "text-dark" do %><i class="fa-solid fa-house fa-xl"></i><% end %>
        <i class="fa-brands fa-facebook-messenger fa-xl"></i>
        <a type="button" class="text-dark" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          <i class="fa-regular fa-square-plus fa-xl"></i>
        </a>
        <i class="fa-regular fa-compass fa-xl"></i>
        <i class="fa-regular fa-heart fa-xl"></i>

        <div class="dropdown">
          <a class="" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user && current_user.profile_pic.attached? %>
              <%= image_tag current_user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 10%" %>
            <% else %>
              <%= image_tag 'user.png', class: "img-thumbnail rounded-circle", style: "width: 2rem" %>
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= button_to 'Log out', destroy_user_session_path, class: "dropdown-item", method: :delete %>
            </li>
          </ul>
        </div>

      </div>
    </div>
  </div>
</nav>

<%= render 'posts/form', post: Post.new %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySns</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if current_user %>
      <%= render 'layouts/navbar' %>
    <% end %>

    <%= yield %>
    
  </body>
</html>

app/views/posts/_form.html.erb
<div class="modal fade modal-lg" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <%= form_with(model: post) do |form| %>

    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Create new post</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body d-flex">
        <div class="border-end border-secondary mx-2" style="width:60%">
          <%= form.file_field :images, multiple: true, id: "post-images", required: true %>
        </div>

        <div style="width:40%">
          <% if post.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

              <ul>
                <% post.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="my-2">
            <% if current_user.profile_pic.attached? %>
              <%= image_tag current_user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 10%" %>
            <% else %>
              <%= image_tag 'user.png', class: "img-thumbnail rounded-circle", style: "width: 10%" %>
            <% end %>
            <span class="fw-bold mx-2"><%= current_user.username %></span>
          </div>

          <div>
            <%= form.text_area :caption, rows: 8, placeholder: "Write a caption...", class: "form-control border-0", style: "resize:none" %>
          </div>

          <div>
            <%= form.text_field :location, placeholder: "Add location", class: "form-control" %>
          </div>

          <div class="d-flex justify-content-between align-items-center border form-control my-2" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample" style="text-decoration:none">
            <a class="text-dark" style="text-decoration:none">
              Advanced Settings
            </a>
            <i class="fa-solid fa-chevron-down"></i>
          </div>

          <div class="collapse" id="collapseExample">
            <div class="card card-body">
              <div class="form-check form-switch">
                <%= form.check_box :allow_comments, class:"form-check-input", role: "switch", checked: true %>
                <%= form.label :allow_comments, class:"form-check-label", style: "display: block" %>
              </div>

              <div class="form-check form-switch">
                <%= form.check_box :show_likes_count, class:"form-check-input", role: "switch", checked: true %>
                <%= form.label :show_likes_count, class:"form-check-label", style: "display: block" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= form.submit "Post", class:"btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/_liker.html.erb
<div class="d-flex justify-content-between">
  <div class="d-flex">
    <%= image_tag 'user.png', class: "img-thumbnail rounded-circle", style: "width: 2.5rem" %>
    <div class="d-flex flex-column mx-3 justify-content-center">
      <small class="fw-bold" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 10rem">
        <%= liker.username %>
      </small>
    </div>
  </div>

  <%= link_to root_path, class:"btn btn-info", style: "text-decoration:none" do %>
    <small class="fw-bold text-white">Follow</small>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="my-3" id="<%= dom_id post %>">
  <div class="card" style="width: 25rem;">
    <div class="card-header bg-white">
      <div class="d-flex justify-content-between">
        <div>
          <% if post.user.profile_pic.attached? %>
            <%= image_tag post.user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 10%" %>
          <% else %>
            <%= image_tag 'user.png', class: "img-thumbnail rounded-circle", style: "width: 10%" %>
          <% end %>
          <span class="fw-bold mx-2"><%= post.user.username %></span>
        </div>

        <div>
          <div class="dropdown">
            <a
              class="text-dark fs-4"
              style="text-decoration:none"
              href="#"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              ...
            </a>

            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Edit post</a></li>
              <li><a class="dropdown-item" href="#">Delete post</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="card-body">
      <div id="post<%= post.id %>_images" class="carousel slide" data-bs-ride="true">
        <div class="carousel-inner">
          <% post.images.each_with_index do |img, i| %>
            <div class="carousel-item <%= i==0 ? 'active' : '' %>" style="height: 25rem">
              <%= image_tag img, class: "d-block w-100", style: "max-height: 100%; object-fit: cover;" %>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#post<%= post.id %>_images" data-bs-slide="prev">
          <span class="carousel-control-prev-icon bg-dark rounded-circle" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#post<%= post.id %>_images" data-bs-slide="next">
          <span class="carousel-control-next-icon bg-dark rounded-circle" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
        <div class="carousel-indicators" style="position: static">
          <% post.images.each_with_index do |img, i| %>
            <button type="button" data-bs-target="#post<%= post.id %>_images" data-bs-slide-to="<%= i %>" class="bg-dark <%= i==0 ? 'active' : '' %>" <%= i==0 ? 'aria-current="true"' : '' %> aria-label="Slide <%= i+1 %>"></button>
          <% end %>
        </div>
      </div>

      <%= render "posts/post_actions", post: post  %>

      <p class="card-text">
        <span class="fw-bold"><%= post.user.username %></span>
        <%= post.caption %>
      </p>

      <small class="text-muted"><%= time_ago_in_words(post.created_at) %></small>
    </div>
    <div class="card-footer d-flex justify-content-between bg-white">
      <input type="text" class="w-75" placeholder="Add a comment...">
      <a class="text-primary fw-bold" style="text-decoration:none">Post</a>
    </div>
  </div>
</div>

<script>
  document.getElementById("post<%= post.id %>_images").addEventListener("dblclick", function() {
    document.getElementById("post<%= post.id %>actions-likeBtn").click();
  })
</script>

app/views/posts/_post_actions.html.erb
<%= turbo_frame_tag "post#{post.id}actions" do %>
  <div class="d-flex justify-content-start align-items-center gap-1 mb-3">
    <%= button_to toggle_like_path(post_id: post.id), method: :post, style: "border:none; background:none", id: "post#{post.id}actions-likeBtn" do %>
      <i class="<%= post.likes.find_by(user: current_user) ? "fa-solid color-red" : "fa-regular" %> fa-heart fa-xl"></i>
    <% end %>
  </div>
  <a href="#" data-bs-toggle="modal" data-bs-target="#post<%= post.id %>_likesModal" style="text-decoration:none" class="text-dark">
    <small class="fw-bold my-1"><%= pluralize(post.likes.count, "like") %> </small>
  </a>

  <!-- Modal -->
  <div class="modal fade" id="post<%= post.id %>_likesModal" tabindex="-1" aria-labelledby="post<%= post.id %>_likesModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title" id="post<%= post.id %>_likesModalLabel">Post Likes</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="d-flex flex-column gap-3">
            <%= post.likers.each do |liker| %>
              <%= render "posts/liker", liker: liker %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="d-flex justify-content-center mt-4">
  <%= render @post %>
</div>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/story/_stories_list.html.erb
<div class="card d-flex flex-row align-items-center justify-content-center gap-3 px-3" style="width: 25rem; height: 7rem; overflow: scroll">
  <% (0..7).each do %>
    <%= render 'story/story' %>
  <% end %>
</div>

app/views/story/_story.html.erb
<div class="d-flex flex-column justify-content-center align-items-center">
  <%= image_tag 'user.png', class: "img-thumbnail rounded-circle border border-2 border-primary", style: "width: 3.5rem" %>
  <small style="max-width: 3.5rem; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">Username</small>
</div>

app/views/suggestions/_suggestion.html.erb
<div class="d-flex justify-content-between">
  <div class="d-flex">
    <%= image_tag 'user.png', class: "img-thumbnail rounded-circle", style: "width: 2.5rem" %>
    <div class="d-flex flex-column mx-2">
      <small class="fw-bold" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 10rem">hello_world</small>
      <small class="fw-bold text-muted" style="font-size:.7rem; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 10rem">Suggested for you by Instagram as He followed you before</small>
    </div>
  </div>

  <%= link_to root_path, style: "text-decoration:none" do %>
    <small class="fw-bold text-primary">Follow</small>
  <% end %>
</div>

app/views/suggestions/_suggestions_list.html.erb
<div class="border" style="width: 20rem">
  <div class="d-flex flex-row justify-content-between">
    <p class="text-muted fw-bold">Suggestions for you</p>
    <%= link_to root_path, style: "text-decoration:none" do %>
      <small class="fw-bold text-dark">See All</small>
    <% end %>
  </div>
  
  <div class="d-flex flex-column gap-3 px-2">
    <% (0..5).each do %>
      <%= render 'suggestions/suggestion' %>
    <% end %>
  </div>
</div>